# -*- coding: utf-8 -*-
"""crash_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nZa-fI3qGxFSSR-Gk_NbXDR-VBQWDyNh
"""

import pandas as pd

df = pd.read_csv("/mock_data.csv")

pd.set_option("display.max_columns",100)

df.head()

df = df.reset_index()

newdf= df.rename(columns= {'index': "ID"})
newdf

internal_df= newdf[['ID','Crash Time', 'Crash Death Count', 'Crash Severity', 'Crash Total Injury Count', 'Crash Year', 'Vehicle Body Style', 'Vehicle Damage Rating 1 - Severity','Vehicle Damage Rating 2 - Severity', 'Vehicle Make', 'Vehicle Model Name', 'Vehicle Model Year', 'Citation', 'Person Age', 'Person Alcohol Result', 'Person Drug Test Result', 'Person Gender', 'Person Injury Severity' , 'Person Type']]
internal_df

external_df= newdf[['ID', 'Crash Year', 'Day of Week', 'Highway Number', 'Highway System', 'Latitude', 'Light Condition', 'Longitude', 'Surface Condition', 'Surface Type', 'Weather Condition']]
external_df

external_df = external_df.drop(columns = "Surface Type")

external_df





import csv_to_sqlite 

# all the usual options are supported
options = csv_to_sqlite.CsvOptions(typing_style="full", encoding="windows-1250") 
input_files = ["crash_data.csv"] # pass in a list of CSV files
csv_to_sqlite.write_csv(input_files, "output.sqlite", options)

